---
- hosts: xds
  gather_facts: yes
  connection: local
  name: System Firmware Update for HPE Cray XD225v, HPE Cray XD295v, HPE Cray XD220v, HPE Cray XD665 and HPE Cray XD670 model systems
  
  vars:
    bmc_username: "{{ inputs[inventory_hostname].user }}"
    bmc_password: "{{ inputs[inventory_hostname].password }}"
    baseuri: "{{ ansible_ssh_host }}"

  tasks:    
    - name: Power states of the nodes will be uploaded to the below csv file
      set_fact: 
        output_file: "Power_State_CrayXD670_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.csv"
      run_once: True
   
    - name: Getting Power State of Cray XD670 Server nodes
      get_power_state:
        category: Get_Power_State
        command: Get_PS
        baseuri: "{{ baseuri }}"
        username: "{{ bmc_username }}"
        password: "{{ bmc_password }}"
        output_file_name: "{{ output_file }}"
      register: system_fw_update_output

    - name: Writing Firmware Upgrade status details to {{output_file}} file
      shell: echo {{system_fw_update_output.msg}} >> {{ output_file }}
